// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMuWVm8XdVQLcTvnmnNvH87oLjjOt9OaY',
    appId: '1:775719617484:web:cb83f8407b7f6752b7d369',
    messagingSenderId: '775719617484',
    projectId: 'gallikart-516f2',
    authDomain: 'gallikart-516f2.firebaseapp.com',
    storageBucket: 'gallikart-516f2.firebasestorage.app',
    measurementId: 'G-GH1MJ4JTTT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB8WKAgwOiBKQa_kUBM0OaMMqQ1gLW8Bs',
    appId: '1:775719617484:android:a777dc32a45e372db7d369',
    messagingSenderId: '775719617484',
    projectId: 'gallikart-516f2',
    storageBucket: 'gallikart-516f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLa_68AgHyuiTB9epSN8lVTi8O0FRJQXU',
    appId: '1:775719617484:ios:c2fa014436339f04b7d369',
    messagingSenderId: '775719617484',
    projectId: 'gallikart-516f2',
    storageBucket: 'gallikart-516f2.firebasestorage.app',
    iosBundleId: 'com.example.gallikart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLa_68AgHyuiTB9epSN8lVTi8O0FRJQXU',
    appId: '1:775719617484:ios:c2fa014436339f04b7d369',
    messagingSenderId: '775719617484',
    projectId: 'gallikart-516f2',
    storageBucket: 'gallikart-516f2.firebasestorage.app',
    iosBundleId: 'com.example.gallikart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMuWVm8XdVQLcTvnmnNvH87oLjjOt9OaY',
    appId: '1:775719617484:web:e0d7c75442d33545b7d369',
    messagingSenderId: '775719617484',
    projectId: 'gallikart-516f2',
    authDomain: 'gallikart-516f2.firebaseapp.com',
    storageBucket: 'gallikart-516f2.firebasestorage.app',
    measurementId: 'G-GEXBWXBCZK',
  );
}
